name: Test workflow
on:
  issues:
    types: [edited]

jobs:
  test-workflow:
    permissions: write-all
    name: Test workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Update issue body
        if: github.event.sender.type != 'Bot'
        run: |
          issue_body=$"${{ github.event.issue.body }}"
          new_issue_body=$""
          while read -r line; do
              line=$(echo "${line}" | tr -d '\n\t\r' | sed "s/$/ - test addition/")
              new_issue_body+=$(echo "$line\r")
          done <<< "$issue_body"
          new_issue_body=$(echo "$new_issue_body" | tr '\n' ' ')
          mutation_query="mutation (\$input: UpdateIssueInput!) {
              updateIssue(input: \$input) {
                  issue {
                      body
                  }
              }
          }"
          mutation_query_req="{
              \"query\": \"$(echo $mutation_query | sed 's/"/\\"/g')\",
              \"variables\": {
                  \"input\": {
                      \"id\": \"${{github.event.issue.node_id}}\",
                      \"body\": \"$(echo -n $new_issue_body | sed 's/"/\\"/g')\"
                  }
              }
          }"

          if [[ ${{ github.event.sender.type }} != "Bot" ]]; then
              curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d "$(echo -n $mutation_query_req | tr -d '\n\t\r')" https://api.github.com/graphql
          fi
